import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bounce, ToastContainer } from 'react-toastify';

import "./globals.css";

import { AdminSidebar } from "@/components/AdminSideBar";
import { SidebarProvider } from "@/components/ui/sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          draggable
          theme="light"
          transition={Bounce}
        />


        <SidebarProvider defaultOpen={true}>

          <AdminSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
